Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,19 +45,18 @@ jobs:
        gunzip -v *.img.gz || echo 0
        mv *.img rpi.img
        kpartx="$(sudo kpartx -avs rpi.img)"
-       read -r img_boot_dev img_root_dev <<<$(grep -o 'loop.p.' <<<"$kpartx")
+       read -r boot root <<<$(grep -o 'loop.p.' <<<"$kpartx")
        sleep 0.5
-       env
-       echo img_root_dev: $img_boot_dev img_root_dev: $img_root_dev
-       img_boot_dev=/dev/mapper/$img_boot_dev
-       img_root_dev=/dev/mapper/$img_root_dev
+       echo boot: $boot root: $root
+       img_boot_dev=/dev/mapper/$boot
+       img_root_dev=/dev/mapper/$root
        sudo mkdir -p /mnt/rpi4
-       sudo mount -t ext4 $img_root_dev /mnt/rpi4 || die "Could not mount $img_root_dev /mnt/rpi4"
+       sudo mount -t ext4 $root /mnt/rpi4 || die "Could not mount $root /mnt/rpi4"
        sudo mkdir -p /mnt/rpi4/boot || die "Could not mkdir /mnt/rpi4/boot"
-       sudo mount -t vfat $img_boot_dev /mnt/rpi4/boot || die "Could not mount $img_boot_dev /mnt/rpi4/boot"
+       sudo mount -t vfat $boot /mnt/rpi4/boot || die "Could not mount $boot /mnt/rpi4/boot"
        cp -a "$(type -p qemu-arm-static)" /mnt/rpi4/usr/bin/ || die "Could not copy qemu-arm-static"
-       echo "Raspbian Image Details:"
-       df -h /mnt/rpi4/boot mnt/rpi4 | sed -e "s#$(pwd)/##"
+       echo "OpenWRT Image Details:"
+       df -h /mnt/rpi4/boot /mnt/rpi4 | sed -e "s#$(pwd)/##"
       
 # jobs:
 #   update:
